apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-blue-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            add_header Content-Type text/html;
            return 200 "<html><body style='background-color: blue;'><h1>Blue Page</h1><p>Hostname: $hostname</p></body></html>";
        }

        location /curl {
            return 200 'Blue Page';
        }
    }
